name: CI

on:
  push:
    branches: [ main, develop, copilot/** ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm ci
    
    - name: Install client dependencies
      run: cd client && npm ci
    
    - name: Lint backend code
      run: npm run lint
    
    - name: Build and lint client code
      run: npm run lint:client
    
    - name: Run client tests
      run: npm run test:client
    
    - name: Check server syntax
      run: node --check server.js
